### PR TITLE
Adding in new levels

### PR DESCRIPTION
**Pull request by AaronCritchley**
Feature preview: https://github.com/AaronCritchley/3030/tree/adding-new-levels (edit by @szhu)

---

**Do not merge!**

Hey @szhu, I though it would be cool if the game had some extra levels so I drafted up a few levels and some text to fill the gaps. I'm open to discussion about how you'd prefer this to be done as my experience with Python is pretty limited to scripting. Let me know what changes you'd like me to make and I'll be happy to go ahead and make them :+1:

### CODE REVIEW

**Comment by szhu** [comment]
> screen shot 2015-09-22 at 5 01 05 am

I hate you so much right now

**Comment by szhu** [comment]
Love your work! I'll merge it in a few hours because I should be asleep.

I will likely need to makes some changes – not to your map, which is great! – but to the Python code, as you suggested, just for future maintainability. I'll also probably squash your commits into a single commit (if you could do that for me, even better, but if not no worries), but it will still be credited to you. I'll make my modifications in the merge commit.

**Comment by szhu** [comment]
Just kidding, who needs sleep?

Your commits (and one of mine) have been merged into `master` at 0728cde4731e695860eb35989408c2732c86e94d. I've rebased your commits and squashed some of them together, but the changes made by them is identical to what you've proposed. The commits that are derived from your original commits are still credited to you.

Thanks for your contribution!

**Comment by AaronCritchley** [comment]
Awesome work, very fast as well! Although you probably should get some sleep!

If any feature requests come up and you're busy feel free to tag me and I'll be happy to take some weight off your shoulders.

**Pull request closed without merging**
