### PR TITLE
Better game.map

### PR DESCRIPTION
**Pull request by Crayder**
Generated with my random map generator.

### CODE REVIEW

**Comment by szhu** [comment]
Thanks for your suggestion! Please do the following to update the README:

``` shell
cd src
make
```

Then commit `README.md` and push it to your branch.

``` shell
cd ..  # if you were in src
git add README.md
git commit -m "Update README.md: Better game.map"
git push
```

**Comment by szhu** [comment]
It's okay, I updated the README myself. The game is much harder now… I like it!

Thanks for our contribution!

**Comment by Crayder** [comment]
I was going to do it when I got home, I only mess with Python when I'm booted into Linux.

**Comment by szhu** [comment]
Ah, I see. No worries, and thanks again!

**Pull request merged**
